### PR TITLE
Add 'robert' to team_names

### PR DESCRIPTION
**Pull request by robertjhull**
### What this PR does (required):
- add 'robert' to team_names in sample.env

### Screenshots / Videos (required):
team-names

### Any information needed to test this feature (required):
- n/a

### CODE REVIEW

**Review by moffatethan — APPROVED** [review]

**Comment by moffatethan** [comment]
We'll just have to solve the merge conflict here before merging Robert! 😄

**Comment by VAggrippino** [comment]
hehe I got mine in first, so there were no merge conflicts :grin: 
I think the point of that exercise was to create a situation in which one of us would have a merge conflict.

Unfortunately, I've had a lot of experience with merge conflicts. They can get pretty bad, but this one won't be. If you guys would like, I can hop in on a call and explain the conflict file and the meanings of the symbols and codes.

**Comment by moffatethan** [comment]
@robertjhull Just giving you a ping on this, if we could get this merged that's fine or I can just close this PR it's up to you 😄

**Comment by robertjhull** [comment]
@moffatethan just merged it.

**Pull request merged**
